### ISSUE TITLE
Supporting emails with plain text along HTML content type

### ISSUE THREAD

**Issue by hailigsblechle** [PeterWarrington/olm-convert#2]
Hi, 
thank you for the development of this OLM mailbox to EML converter.
If I understand correctly, the description says it can only output emails with HTML content type.
Is there a possibility to support plain text emails? Could you state the challenges with exporting plain text emails?

Thanks and best regards
hailigblechle

**Comment by PeterWarrington** [comment]
Thank you, it is not that challenging given the codebase I have already written, merely requiring a couple of extra lines. I hope to add the feature soon, and will get back to you when I do.

**Comment by PeterWarrington** [comment]
After further testing, the program is able to read and export plain-text emails at present, but only as HTML embedded within eml files. Does this meet your requirements?

**Comment by PeterWarrington** [comment]
I have made changes such that exported emails now contain plain-text, alongside any HTML content: https://github.com/PeterWarrington/olm-convert/commit/79273aa32b60c372b0c6605f3bd1cd9aa0edc281

For example, an exported EML file now looks like:

```
...
--B_1
Content-type: multipart/alternative;
	boundary="B_2"

--B_2
Content-type: text/plain;
	charset="UTF-8"
Content-transfer-encoding: quoted-printable

test

--B_2
Content-type: text/html;
	charset="UTF-8"
Content-transfer-encoding: quoted-printable

<b>test</b>
--B_2--
--B_1--
```

Does this meet your requirements?
